import { MaterialCommunityIcons } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import React, { useState } from "react";
import {
  ActivityIndicator,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useApp } from "@/context/AppContext";
import { useColors } from "@/hooks/useColors";

export default function CVScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { profile, certificates, passportCDC } = useApp();
  const [isExporting, setIsExporting] = useState(false);
  const styles = makeStyles(colors);

  const hasProfile = profile && profile.name;

  function generateHTML(): string {
    const p = profile!;
    const certsHtml = certificates.map(c => `
      <tr>
        <td>${c.name}</td>
        <td>${c.issuingBody || "—"}</td>
        <td>${c.issueDate || "—"}</td>
        <td>${c.expiryDate}</td>
      </tr>
    `).join("");

    return `
    <!DOCTYPE html><html><head>
    <meta charset="utf-8"/>
    <style>
      body { font-family: Arial, sans-serif; margin: 40px; color: #1A2B3C; }
      h1 { color: #0A2342; font-size: 26px; margin-bottom: 4px; }
      .subtitle { color: #6B7A8D; font-size: 16px; margin-bottom: 8px; }
      .contact { color: #6B7A8D; font-size: 13px; margin-bottom: 24px; }
      h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #0A2342; 
           border-bottom: 2px solid #D4AF37; padding-bottom: 4px; margin-top: 24px; }
      .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px 24px; margin: 12px 0; }
      .info-item { font-size: 13px; }
      .info-label { font-weight: 600; color: #6B7A8D; font-size: 11px; text-transform: uppercase; }
      table { width: 100%; border-collapse: collapse; margin-top: 12px; }
      th { background: #0A2342; color: white; padding: 8px 12px; text-align: left; font-size: 12px; }
      td { padding: 8px 12px; border-bottom: 1px solid #E4ECF4; font-size: 13px; }
      .footer { text-align: center; color: #6B7A8D; font-size: 11px; margin-top: 40px; }
    </style></head><body>
    <h1>${p.name}</h1>
    <div class="subtitle">${p.rank || "Seafarer"}</div>
    <div class="contact">${[p.email, p.phone].filter(Boolean).join(" | ")}</div>

    <h2>Personal Information</h2>
    <div class="info-grid">
      <div class="info-item"><div class="info-label">Date of Birth</div>${p.dateOfBirth || "—"}</div>
      <div class="info-item"><div class="info-label">Nationality</div>${p.nationality || "—"}</div>
      <div class="info-item"><div class="info-label">National ID</div>${p.nid || "—"}</div>
      <div class="info-item"><div class="info-label">Blood Group</div>${p.bloodGroup || "—"}</div>
      ${passportCDC?.passportNumber ? `<div class="info-item"><div class="info-label">Passport No.</div>${passportCDC.passportNumber}</div>` : ""}
      ${passportCDC?.cdcNumber ? `<div class="info-item"><div class="info-label">CDC No.</div>${passportCDC.cdcNumber}</div>` : ""}
    </div>

    ${certificates.length > 0 ? `
    <h2>Certificates &amp; Qualifications</h2>
    <table>
      <thead><tr><th>Certificate</th><th>Issuing Body</th><th>Issue Date</th><th>Expiry</th></tr></thead>
      <tbody>${certsHtml}</tbody>
    </table>` : ""}

    <div class="footer">Generated by Seaman Wallet &mdash; ${new Date().toLocaleDateString()}</div>
    </body></html>
    `;
  }

  async function handleExport() {
    if (!hasProfile) return;
    if (Platform.OS !== "web") Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setIsExporting(true);
    try {
      const { uri } = await Print.printToFileAsync({ html: generateHTML() });
      if (Platform.OS !== "web" && (await Sharing.isAvailableAsync())) {
        await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Share CV" });
      } else {
        await Print.printAsync({ uri });
      }
    } catch {
      // fallback to print dialog
      try {
        await Print.printAsync({ html: generateHTML() });
      } catch {}
    } finally {
      setIsExporting(false);
    }
  }

  if (!hasProfile) {
    return (
      <View style={[styles.emptyContainer, { paddingBottom: insets.bottom }]}>
        <MaterialCommunityIcons name="file-account-outline" size={64} color={colors.mutedForeground} />
        <Text style={[styles.emptyTitle, { color: colors.foreground }]}>Profile Required</Text>
        <Text style={[styles.emptyText, { color: colors.mutedForeground }]}>
          Complete your profile first to generate your CV automatically.
        </Text>
      </View>
    );
  }

  const p = profile!;
  const certsToShow = certificates.slice(0, 8);

  return (
    <ScrollView
      contentContainerStyle={[styles.container, { paddingBottom: insets.bottom + 32 }]}
    >
      {/* CV Preview Card */}
      <View style={[styles.cvCard, { borderColor: "#D4AF3780", borderWidth: 1.5 }]}>
        {/* Header */}
        <View style={[styles.cvHeader, { backgroundColor: colors.primary }]}>
          <View style={styles.cvHeaderInner}>
            <Text style={styles.cvName}>{p.name}</Text>
            <Text style={styles.cvRank}>{p.rank || "Seafarer"}</Text>
            <Text style={styles.cvContact}>
              {[p.email, p.phone].filter(Boolean).join("  |  ")}
            </Text>
          </View>
          <View style={styles.cvAccent}>
            <MaterialCommunityIcons name="anchor" size={36} color="#D4AF37" />
          </View>
        </View>

        {/* Personal Info */}
        <View style={styles.section}>
          <Text style={[styles.sectionTitle, { color: colors.primary }]}>Personal Information</Text>
          <View style={styles.infoGrid}>
            <InfoItem label="Date of Birth" value={p.dateOfBirth || "—"} />
            <InfoItem label="Nationality" value={p.nationality || "—"} />
            <InfoItem label="National ID" value={p.nid || "—"} />
            <InfoItem label="Blood Group" value={p.bloodGroup || "—"} />
            {passportCDC?.passportNumber && (
              <InfoItem label="Passport No." value={passportCDC.passportNumber} />
            )}
            {passportCDC?.cdcNumber && (
              <InfoItem label="CDC No." value={passportCDC.cdcNumber} />
            )}
          </View>
        </View>

        {/* Certificates */}
        {certsToShow.length > 0 && (
          <View style={styles.section}>
            <Text style={[styles.sectionTitle, { color: colors.primary }]}>Certificates</Text>
            {certsToShow.map((cert) => (
              <View key={cert.id} style={[styles.certRow, { borderColor: colors.border }]}>
                <MaterialCommunityIcons name="certificate" size={16} color={colors.ocean} style={{ marginTop: 1 }} />
                <View style={{ flex: 1 }}>
                  <Text style={[styles.certName, { color: colors.foreground }]}>{cert.name}</Text>
                  <Text style={[styles.certMeta, { color: colors.mutedForeground }]}>
                    {cert.issuingBody ? `${cert.issuingBody} · ` : ""}Expires {cert.expiryDate}
                  </Text>
                </View>
              </View>
            ))}
          </View>
        )}

        <View style={styles.cvFooter}>
          <Text style={[styles.cvFooterText, { color: colors.mutedForeground }]}>
            Generated by Seaman Wallet · {new Date().toLocaleDateString()}
          </Text>
        </View>
      </View>

      {/* Export Button */}
      <Pressable
        style={({ pressed }) => [styles.exportBtn, { backgroundColor: colors.primary, opacity: pressed ? 0.85 : 1 }]}
        onPress={handleExport}
        disabled={isExporting}
      >
        {isExporting ? (
          <ActivityIndicator color="#fff" />
        ) : (
          <>
            <MaterialCommunityIcons name="file-export" size={20} color="#fff" />
            <Text style={styles.exportBtnText}>Export PDF</Text>
          </>
        )}
      </Pressable>

      <Text style={[styles.hint, { color: colors.mutedForeground }]}>
        Your CV is generated from profile and certificate data. Update your profile to refresh.
      </Text>
    </ScrollView>
  );
}

function InfoItem({ label, value }: { label: string; value: string }) {
  const colors = useColors();
  return (
    <View style={{ marginBottom: 10 }}>
      <Text style={{ fontSize: 10, fontWeight: "700", color: colors.mutedForeground, textTransform: "uppercase", letterSpacing: 0.5 }}>{label}</Text>
      <Text style={{ fontSize: 14, color: colors.foreground, marginTop: 2 }}>{value}</Text>
    </View>
  );
}

function makeStyles(colors: ReturnType<typeof useColors>) {
  return StyleSheet.create({
    container: { padding: 16, gap: 16 },
    emptyContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 32,
      gap: 16,
    },
    emptyTitle: { fontSize: 20, fontWeight: "700" },
    emptyText: { fontSize: 14, textAlign: "center", lineHeight: 22 },
    cvCard: {
      backgroundColor: colors.card,
      borderRadius: 16,
      overflow: "hidden",
    },
    cvHeader: {
      flexDirection: "row",
      padding: 20,
      alignItems: "center",
    },
    cvHeaderInner: { flex: 1 },
    cvName: { fontSize: 22, fontWeight: "800", color: "#fff", marginBottom: 4 },
    cvRank: { fontSize: 14, color: "rgba(255,255,255,0.8)", marginBottom: 6 },
    cvContact: { fontSize: 11, color: "rgba(255,255,255,0.65)" },
    cvAccent: {
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: "rgba(255,255,255,0.1)",
      alignItems: "center",
      justifyContent: "center",
    },
    section: {
      padding: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 12,
    },
    infoGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 0,
    },
    certRow: {
      flexDirection: "row",
      gap: 10,
      paddingVertical: 8,
      borderBottomWidth: 1,
    },
    certName: { fontSize: 13, fontWeight: "600" },
    certMeta: { fontSize: 11, marginTop: 2 },
    cvFooter: { padding: 12, alignItems: "center" },
    cvFooterText: { fontSize: 11 },
    exportBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      borderRadius: 14,
      paddingVertical: 16,
    },
    exportBtnText: { fontSize: 16, fontWeight: "700", color: "#fff" },
    hint: { fontSize: 12, textAlign: "center", lineHeight: 18 },
  });
}
